### PR TITLE
Fix month format at Toolbar

### LINKED ISSUE #48: Improve how the Names of months are show
In mobile devices, the names of months are not shown correctly, maybe just show the first three letters os word

AGO  SET OUT 

to show better

### PR DESCRIPTION
**Pull request by capaci**
This closes #48 

I've change the string format of `state_month_str`, `next_month_str` and `previous_month_str` from 'MMMM YY' to 'MMM YY', to show only the first three letters of the months and the year. Eg: `AGO 18`

### CODE REVIEW

**Comment by davidcostadev** [comment]
You just to need to update the snapshot

**Comment by capaci** [comment]
@davidcostadev done :)

**Comment by davidcostadev** [comment]
It is need to fix on the e2e tests too.

**Comment by capaci** [comment]
@davidcostadev I've update the test files, but travis keeps failing. Could you help me with that?

**Comment by capaci** [comment]
thanks @davidcostadev

**Pull request merged**
